environment:
  nodejs_version: "8"

services:
  - mongodb

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g yarn
  - cd packages; sh start.sh

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
