version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8.5.0-browsers
      - image: mongo:3.4.4
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "package.json" }}
      - restore_cache:
          key: sut-{{ checksum "sut/package.json" }}
      - run:
          name: Setup and test
          command: |
            yarn
            yarn run setup
            yarn run test
      - save_cache:
          key: node-modules-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: sut-{{ checksum "sut/package.json" }}
          paths:
            - ./sut
      - store_artifacts:
          path: ./.screenshots
          destination: screenshots


workflows:
  version: 2
  test:
    jobs:
      - test
