version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.5.0-browsers
      - image: circleci/mongo:3.4.9
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: sut-node-modules-{{ checksum "packages/yarn.lock" }}
      - run:
          name: Setup greenkeeper-lockfile
          command: |
            sudo npm install -g greenkeeper-lockfile@1
            which greenkeeper-lockfile-update greenkeeper-lockfile-upload
            greenkeeper-lockfile-update
      - run:
          name: Start app and test
          command: |
            yarn
            yarn run start
            yarn run test
      - run:
          name: Upload greenkeeper-lockfile
          command: |
            greenkeeper-lockfile-upload
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - save_cache:
          key: sut-node-modules-{{ checksum "packages/yarn.lock" }}
          paths:
            - ./packages/node_modules/
      - store_artifacts:
          path: ./.screenshots
          destination: screenshots
