version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.5
      - image: mongo:3.4.4
      - image: cypress/internal:cy-0.19.4
        environment:
          TERM: xterm   ## Enable colors in the output

    steps:
      - checkout
      - run:
          name: Setup
          command: yarn run setup
      - run:
          name: Test
          command: yarn test
      - store_artifacts:
          path: cypress/videos/

workflows:
  version: 2
  test:
    jobs:
      - test
