version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8.5.0-browsers
      - image: circleci/mongo:3.4.9
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: sut-node-modules-{{ checksum "sut/yarn.lock" }}
      - run:
          name: Start app and test
          command: |
            yarn
            yarn run start
            yarn run test
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - save_cache:
          key: sut-node-modules-{{ checksum "sut/yarn.lock" }}
          paths:
            - ./sut/node_modules/
      - store_artifacts:
          path: ./.screenshots
          destination: screenshots

workflows:
  version: 2
  test:
    jobs:
      - test
