version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8.5.0
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Setup and test
          command: |
            yarn run setup
            yarn run test

workflows:
  version: 2
  test:
    jobs:
      - test
