version: 2
jobs:
  test:
    docker:
      - image: cypress/internal:cy-0.19.4
        environment:
          TERM: xterm   ## Enable colors in the output
      - image: mongo:3.4.4

    steps:
      - checkout
      - run:
          name: Setup and test
          command: |
            yarn run setup
            yarn run test
      - store_artifacts:
          path: cypress/screenshots/
      - store_artifacts:
          path: cypress/videos/

workflows:
  version: 2
  test:
    jobs:
      - test
