version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.5
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Setup
          command: yarn
          command: yarn run setup
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test
